create database drones;
use drones;
create table points(id int(11) unsigned auto_increment primary key not null,pointID int(16) not null,x int(16) not null,y int(16) not null,z int(16) not null,transitpoint bool not null);
insert into points(pointID, x,y,z) values(0,0,0,0);
insert into points(pointID, x,y,z) values(1,1,0,0);
insert into points(pointID, x,y,z) values(2,2,0,0);
insert into points(pointID, x,y,z) values(3,3,0,0);
insert into points(pointID, x,y,z) values(4,4,0,0);
insert into points(pointID, x,y,z) values(5,5,3,0);
create table drones(id int(11) unsigned auto_increment primary key not null,droneID int(11) not null, x int(16) not null,y int(16) not null, z int(16) not null);
